Vagrant.configure(2) do |config|

  config.ssh.insert_key = false
  config.vm.box = "centos/7"
  config.vm.box_check_update = true
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end

  config.vm.define "kalinux.jexia.com" do |node|
    node.vm.hostname = "kalinux.jexia.com"
    node.vm.network "private_network", ip: "192.168.33.11"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    config.vm.provider "libvirt" do |vl|
      vl.memory = 1024
      vl.cpus = 1
    end
  end
end
